In [78]:
import pandas as pd 
import numpy as np

In [79]:
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/titanic.csv")

In [80]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [81]:
df[0:100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [82]:
#implicit indexing
df.iloc[0:2] #stert  from 0 and go to till 1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [83]:
df.loc[0:2] # loc is used for named indexes, iloc is used for interger indexing

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [84]:
df.loc[0:2, ['Name','Parch']]

                                                Name  Parch
0                            Braund, Mr. Owen Harris      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0
2                             Heikkinen, Miss. Laina      0

In [85]:
df.iloc[0:2, 3:6]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0

In [86]:
df['Name'][2:5]

2                          Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                        Allen, Mr. William Henry
Name: Name, dtype: object

In [87]:
list(df['Name'][2:5])

['Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [88]:
s= pd.Series(list(df['Name'][2:5]), index=['a','b','c'])

In [89]:
s

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
dtype: object

In [90]:
s1=pd.Series(list(df['Name'][5:8]))

In [91]:
s1

0                  Moran, Mr. James
1           McCarthy, Mr. Timothy J
2    Palsson, Master. Gosta Leonard
dtype: object

In [92]:
s1=pd.Series(list(df['Name'][5:8]), index=['a','b','c'])

In [93]:
#series and dataframe cannot be concatenated
#if you keep the index same, then for series concatenation can happen
s1

a                  Moran, Mr. James
b           McCarthy, Mr. Timothy J
c    Palsson, Master. Gosta Leonard
dtype: object

In [94]:
s

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
dtype: object

In [95]:
s+s1

a               Heikkinen, Miss. LainaMoran, Mr. James
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)Mc...
c    Allen, Mr. William HenryPalsson, Master. Gosta...
dtype: object

In [96]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [97]:
#drop a column
df.drop('PassengerId', axis=1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [98]:
df.drop('PassengerId', axis=1, inplace= True)

In [99]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [100]:
df.drop(1, inplace=True)

In [101]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
151,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [102]:
df.reset_index(drop = True)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
150,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
151,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
152,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
153,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
154,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [103]:
df.set_index('Name', inplace=True)

In [104]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Pears, Mrs. Thomas (Edith Wearne)",1,1,female,22.0,1,0,113776,66.6000,C2,S
"Meo, Mr. Alfonzo",0,3,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
"van Billiard, Mr. Austin Blyler",0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
"Olsen, Mr. Ole Martin",0,3,male,NaN,0,0,Fa 265302,7.3125,NaN,S
"Williams, Mr. Charles Duane",0,1,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [105]:
df.loc['Braund, Mr. Owen Harris']

Survived            0
Pclass              3
Sex              male
Age              22.0
SibSp               1
Parch               0
Ticket      A/5 21171
Fare             7.25
Cabin             NaN
Embarked            S
Name: Braund, Mr. Owen Harris, dtype: object

In [106]:
df.reset_index(inplace=True)

In [107]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
150,"Pears, Mrs. Thomas (Edith Wearne)",1,1,female,22.0,1,0,113776,66.6000,C2,S
151,"Meo, Mr. Alfonzo",0,3,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
152,"van Billiard, Mr. Austin Blyler",0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
153,"Olsen, Mr. Ole Martin",0,3,male,NaN,0,0,Fa 265302,7.3125,NaN,S
154,"Williams, Mr. Charles Duane",0,1,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [108]:
d ={'key1':[1,2,3,4],
    'key2': [5,6,7,8],
    'key3': [2,3,7,8]}

In [109]:
d

{'key1': [1, 2, 3, 4], 'key2': [5, 6, 7, 8], 'key3': [2, 3, 7, 8]}

In [110]:

pd.DataFrame(d)

   key1  key2  key3
0     1     5     2
1     2     6     3
2     3     7     7
3     4     8     8

In [111]:
d ={'key1':(1,2,3,4),
    'key2': (5,6,7,8),
    'key3': (2,3,7,8)}

In [112]:
d

{'key1': (1, 2, 3, 4), 'key2': (5, 6, 7, 8), 'key3': (2, 3, 7, 8)}

In [113]:
pd.DataFrame(d)

   key1  key2  key3
0     1     5     2
1     2     6     3
2     3     7     7
3     4     8     8

In [114]:
df1 = pd.read_csv("taxonomy.csv")

In [115]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [116]:
df1.shape

(290, 4)

In [117]:
df1.describe()

       taxonomy_id          name  parent_id       parent_name
count          290           290        279               279
unique         290           183         60                50
top            101  Nursing Home  106-06-07  Health Education
freq             1             4         11                15

In [118]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   taxonomy_id  290 non-null    object
 1   name         290 non-null    object
 2   parent_id    279 non-null    object
 3   parent_name  279 non-null    object
dtypes: object(4)
memory usage: 9.2+ KB

In [119]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [120]:
df1.isnull().sum()

taxonomy_id     0
name            0
parent_id      11
parent_name    11
dtype: int64

In [121]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [122]:
df1.dropna() # remove null values row wise

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [123]:
df1.dropna(axis = 1)

    taxonomy_id                          name
0           101                     Emergency
1        101-01             Disaster Response
2        101-02                Emergency Cash
3     101-02-01             Help Pay for Food
4     101-02-02       Help Pay for Healthcare
..          ...                           ...
285   111-01-07              Workplace Rights
286      111-02                     Mediation
287      111-03                        Notary
288      111-04                Representation
289      111-05  Translation & Interpretation

[290 rows x 2 columns]

In [124]:
df1[['name']].dropna(axis=1) # for one column

                             name
0                       Emergency
1               Disaster Response
2                  Emergency Cash
3               Help Pay for Food
4         Help Pay for Healthcare
..                            ...
285              Workplace Rights
286                     Mediation
287                        Notary
288                Representation
289  Translation & Interpretation

[290 rows x 1 columns]

In [125]:
#imputation of missing valu 
# numaric data>> mean and median>> outliar treatment done>> mean else median
# catagorical>> mode
# impute misssing valu may be with some constent >> 0

In [126]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [127]:
df1.fillna("0")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency         0                     0
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [128]:
df1.fillna("somevalu")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency  somevalu              somevalu
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [129]:
df1.parent_id

0         NaN
1         101
2         101
3      101-02
4      101-02
        ...
285    111-01
286       111
287       111
288       111
289       111
Name: parent_id, Length: 290, dtype: object

In [130]:
data1 = {
    'A' : [1, 2, None, 4, 5, None, 7, 8, 9, 10],
    'B' : [None, 11, 12, 13, None, 15, 16, None, 18, 19]
}

df2 = pd.DataFrame(data1)
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [131]:
df2.A

0     1.0
1     2.0
2     NaN
3     4.0
4     5.0
5     NaN
6     7.0
7     8.0
8     9.0
9    10.0
Name: A, dtype: float64

In [132]:
df2.A.fillna(df2['A'].mean())

0     1.00
1     2.00
2     5.75
3     4.00
4     5.00
5     5.75
6     7.00
7     8.00
8     9.00
9    10.00
Name: A, dtype: float64

In [133]:
df2.A.fillna(df2['A'].median())

0     1.0
1     2.0
2     6.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: A, dtype: float64

In [134]:
df2.A.fillna(df2['A'].mode())

0     1.0
1     2.0
2     4.0
3     4.0
4     5.0
5     8.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: A, dtype: float64

In [135]:
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [136]:
df2.fillna(0)

      A     B
0   1.0   0.0
1   2.0  11.0
2   0.0  12.0
3   4.0  13.0
4   5.0   0.0
5   0.0  15.0
6   7.0  16.0
7   8.0   0.0
8   9.0  18.0
9  10.0  19.0

In [137]:
df2.fillna('something')

           A          B
0        1.0  something
1        2.0       11.0
2  something       12.0
3        4.0       13.0
4        5.0  something
5  something       15.0
6        7.0       16.0
7        8.0  something
8        9.0       18.0
9       10.0       19.0

In [138]:
df2.fillna(method='ffill') #forword fill >> start seeing from the bottom of dataframe and fill with the next value observed

C:\Users\sujay\AppData\Local\Temp\ipykernel_18996\1047838960.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill') #forword fill >> start seeing from the bottom of dataframe and fill with the next value observed

      A     B
0   1.0   NaN
1   2.0  11.0
2   2.0  12.0
3   4.0  13.0
4   5.0  13.0
5   5.0  15.0
6   7.0  16.0
7   8.0  16.0
8   9.0  18.0
9  10.0  19.0

In [139]:
df2.fillna(method='bfill') # backword fill >> see from top and fill with next observed value

C:\Users\sujay\AppData\Local\Temp\ipykernel_18996\1548114720.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill') # backword fill >> see from top and fill with next observed value

      A     B
0   1.0  11.0
1   2.0  11.0
2   4.0  12.0
3   4.0  13.0
4   5.0  15.0
5   7.0  15.0
6   7.0  16.0
7   8.0  18.0
8   9.0  18.0
9  10.0  19.0

In [140]:
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [141]:
df2.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [142]:
df2.duplicated().sum()

0

In [143]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
150,"Pears, Mrs. Thomas (Edith Wearne)",1,1,female,22.0,1,0,113776,66.6000,C2,S
151,"Meo, Mr. Alfonzo",0,3,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
152,"van Billiard, Mr. Austin Blyler",0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
153,"Olsen, Mr. Ole Martin",0,3,male,NaN,0,0,Fa 265302,7.3125,NaN,S
154,"Williams, Mr. Charles Duane",0,1,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [144]:
df2.mean()

A     5.750000
B    14.857143
dtype: float64

In [145]:
df2.median()

A     6.0
B    15.0
dtype: float64

In [146]:
df2.std()

A    3.284161
B    3.023716
dtype: float64

In [147]:
df.Age.describe()

count    125.000000
mean      28.062640
std       14.645741
min        0.830000
25%       19.000000
50%       26.000000
75%       35.000000
max       71.000000
Name: Age, dtype: float64

In [148]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
150,"Pears, Mrs. Thomas (Edith Wearne)",1,1,female,22.0,1,0,113776,66.6000,C2,S
151,"Meo, Mr. Alfonzo",0,3,male,55.5,0,0,A.5. 11206,8.0500,NaN,S
152,"van Billiard, Mr. Austin Blyler",0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
153,"Olsen, Mr. Ole Martin",0,3,male,NaN,0,0,Fa 265302,7.3125,NaN,S
154,"Williams, Mr. Charles Duane",0,1,male,51.0,0,1,PC 17597,61.3792,NaN,C

In [149]:
#Q. what is the avarage fere paid by people who survived ?

In [150]:
# avarage fare survived
df[df.Survived == 1]['Fare'].mean()

28.908726415094343

In [151]:
# avg fare how didnt survived 
df[df.Survived == 0]['Fare'].mean()

27.271076470588238

In [152]:
# groupby

In [153]:
df.groupby('Survived').mean(numeric_only=True)

            Pclass        Age     SibSp     Parch       Fare
Survived
0         2.490196  29.358824  0.666667  0.372549  27.271076
1         2.320755  25.308250  0.509434  0.452830  28.908726

In [154]:
df.groupby('Survived').min(numeric_only=True)

          Pclass   Age  SibSp  Parch    Fare
Survived
0              1  2.00      0      0  6.7500
1              1  0.83      0      0  7.1417

In [155]:
df.groupby('Survived').sum(numeric_only=True)

          Pclass      Age  SibSp  Parch       Fare
Survived
0            254  2495.50     68     38  2781.6498
1            123  1012.33     27     24  1532.1625

In [156]:
df.groupby('Survived').describe()

         Pclass                                                Age             \
          count      mean       std  min  25%  50%  75%  max count       mean
Survived
0         102.0  2.490196  0.780265  1.0  2.0  3.0  3.0  3.0  85.0  29.358824
1          53.0  2.320755  0.803205  1.0  2.0  3.0  3.0  3.0  40.0  25.308250

          ... Parch        Fare                                                \
          ...   75%  max  count       mean        std     min    25%      50%
Survived  ...
0         ...   0.0  5.0  102.0  27.271076  38.516545  6.7500  8.050  13.7271
1         ...   0.0  5.0   53.0  28.908726  41.329610  7.1417  7.925  15.2458


               75%    max
Survived
0         30.97395  263.0
1         29.00000  263.0

[2 rows x 40 columns]

In [157]:
import numpy as np
df.groupby(['Survived'])['Fare'].agg([min, 'max', 'mean','median', 'count', np.std, 'var'])

C:\Users\sujay\AppData\Local\Temp\ipykernel_18996\32886713.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['Survived'])['Fare'].agg([min, 'max', 'mean','median', 'count', np.std, 'var'])
C:\Users\sujay\AppData\Local\Temp\ipykernel_18996\32886713.py:2: FutureWarning: The provided callable <function std at 0x000001FA000D40E0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df.groupby(['Survived'])['Fare'].agg([min, 'max', 'mean','median', 'count', np.std, 'var'])

             min    max       mean   median  count        std          var
Survived
0         6.7500  263.0  27.271076  13.7271    102  38.516545  1483.524225
1         7.1417  263.0  28.908726  15.2458     53  41.329610  1708.136636

In [161]:
df[['Survived', 'Fare']]

     Survived     Fare
0           0   7.2500
1           1   7.9250
2           1  53.1000
3           0   8.0500
4           0   8.4583
..        ...      ...
150         1  66.6000
151         0   8.0500
152         0  14.5000
153         0   7.3125
154         0  61.3792

[155 rows x 2 columns]

In [169]:
df.groupby(['Sex','Pclass'])['Survived'].sum()

Sex     Pclass
female  1          8
        2         11
        3         20
male    1          3
        2          3
        3          8
Name: Survived, dtype: int64

In [170]:
df.groupby(['Sex','Pclass'])['Survived'].sum().to_frame()

               Survived
Sex    Pclass
female 1              8
       2             11
       3             20
male   1              3
       2              3
       3              8

In [172]:
df.groupby(['Sex','Pclass'])['Survived'].sum().unstack()

Pclass  1   2   3
Sex
female  8  11  20
male    3   3   8

In [174]:
df.groupby('Pclass').sum(numeric_only=True)

        Survived      Age  SibSp  Parch       Fare
Pclass
1             11   991.00     15     12  2313.7749
2             14   815.33     12     10   709.7916
3             28  1701.50     68     40  1290.2458

In [175]:
a = df.groupby('Pclass').sum(numeric_only=True)

In [177]:
a

        Survived      Age  SibSp  Parch       Fare
Pclass
1             11   991.00     15     12  2313.7749
2             14   815.33     12     10   709.7916
3             28  1701.50     68     40  1290.2458

In [179]:
a.T

Pclass            1         2          3
Survived    11.0000   14.0000    28.0000
Age        991.0000  815.3300  1701.5000
SibSp       15.0000   12.0000    68.0000
Parch       12.0000   10.0000    40.0000
Fare      2313.7749  709.7916  1290.2458

In [181]:
a.transpose()

Pclass            1         2          3
Survived    11.0000   14.0000    28.0000
Age        991.0000  815.3300  1701.5000
SibSp       15.0000   12.0000    68.0000
Parch       12.0000   10.0000    40.0000
Fare      2313.7749  709.7916  1290.2458

In [183]:
df.head().T

,0,1,2,3,4
Name,"Braund, Mr. Owen Harris","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James"
Survived,0,1,1,0,0
Pclass,3,3,1,3,3
Sex,male,female,female,male,male
Age,22.0,26.0,35.0,35.0,NaN
SibSp,1,0,1,0,0
Parch,0,0,0,0,0
Ticket,A/5 21171,STON/O2. 3101282,113803,373450,330877
Fare,7.25,7.925,53.1,8.05,8.4583
Cabin,NaN,NaN,C123,NaN,NaN
Embarked,S,S,S,S,Q