In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df1 = df[["Name", "Sex", "Age"]][0:5]

In [5]:
df2 = df[["Name", "Sex", "Age"]][5:10]

In [6]:
# row wise contatenate  >> vaticaly concatenate
pd.concat([df1, df2], axis= 0)  #concatenate pandas objects along a particular axis.

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [7]:
#column wise contatenate >> horizentaly concatenate
pd.concat([df1, df2], axis= 1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [8]:
df1

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [9]:
df2.reset_index(drop= True, inplace= True)
df2

                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                     Palsson, Master. Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [10]:
pd.concat([df1, df2], axis=1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,"Moran, Mr. James",male,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,"McCarthy, Mr. Timothy J",male,54.0
2,"Heikkinen, Miss. Laina",female,26.0,"Palsson, Master. Gosta Leonard",male,2.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
4,"Allen, Mr. William Henry",male,35.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [11]:
df1 = pd.DataFrame({'key1': [1,2,4,5,6],
                     'key2':[4,5,6,7,8],
                     'key3':[3,4,5,6,6]})

In [12]:
df2 = pd.DataFrame({'key1': [1,2,45,6,67],
                     'key4':[56,5,6,7,8],
                     'key5':[3,56,5,6,6]})

In [13]:
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [14]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [15]:
# marge >> key
pd.merge(df1, df2, how = 'inner')

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [16]:
pd.merge(df1, df2, how= 'left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [17]:
df1,df2

(   key1  key2  key3
 0     1     4     3
 1     2     5     4
 2     4     6     5
 3     5     7     6
 4     6     8     6,
    key1  key4  key5
 0     1    56     3
 1     2     5    56
 2    45     6     5
 3     6     7     6
 4    67     8     6)

In [18]:
pd.merge(df1, df2, how= 'right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [19]:
df1,df2

(   key1  key2  key3
 0     1     4     3
 1     2     5     4
 2     4     6     5
 3     5     7     6
 4     6     8     6,
    key1  key4  key5
 0     1    56     3
 1     2     5    56
 2    45     6     5
 3     6     7     6
 4    67     8     6)

In [20]:
pd.merge(df1, df2, how = 'outer' ) # all the keys from both the datafram

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [21]:
pd.merge(df1, df2, how='cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [22]:
pd.merge(df1,df2, how="left", left_on="key1",right_on="key4")

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     3     NaN   NaN   NaN
1       2     5     4     NaN   NaN   NaN
2       4     6     5     NaN   NaN   NaN
3       5     7     6     2.0   5.0  56.0
4       6     8     6    45.0   6.0   5.0

In [23]:
#join >> index 
df1= pd.DataFrame({'key1':[1,2,4,5,6],
    'key2':[4,5,6,7,8],
    'key3':[3,4,5,6,6]},
    index=['a','b','c','d','e']
)

In [24]:
df2= pd.DataFrame({'key6':[1,2,45,6,67],
    'key4':[56,5,6,7,8],
    'key5':[3,56,5,6,6]},
    index=['a','b','h','i','j']
)

In [25]:
df1,df2

(   key1  key2  key3
 a     1     4     3
 b     2     5     4
 c     4     6     5
 d     5     7     6
 e     6     8     6,
    key6  key4  key5
 a     1    56     3
 b     2     5    56
 h    45     6     5
 i     6     7     6
 j    67     8     6)

In [26]:
df1.join(df2, how="inner") #join column of another Datafream

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [27]:
df1.join(df2, how = "left")

   key1  key2  key3  key6  key4  key5
a     1     4     3   1.0  56.0   3.0
b     2     5     4   2.0   5.0  56.0
c     4     6     5   NaN   NaN   NaN
d     5     7     6   NaN   NaN   NaN
e     6     8     6   NaN   NaN   NaN

In [28]:
df1.join(df2, how = "right")

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0     1    56     3
b   2.0   5.0   4.0     2     5    56
h   NaN   NaN   NaN    45     6     5
i   NaN   NaN   NaN     6     7     6
j   NaN   NaN   NaN    67     8     6

In [29]:
df1.join(df2, how = "outer")

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0   1.0  56.0   3.0
b   2.0   5.0   4.0   2.0   5.0  56.0
c   4.0   6.0   5.0   NaN   NaN   NaN
d   5.0   7.0   6.0   NaN   NaN   NaN
e   6.0   8.0   6.0   NaN   NaN   NaN
h   NaN   NaN   NaN  45.0   6.0   5.0
i   NaN   NaN   NaN   6.0   7.0   6.0
j   NaN   NaN   NaN  67.0   8.0   6.0

In [30]:
df1.join(df2, how = "inner")

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [31]:
df1.join(df2, how = "cross")

    key1  key2  key3  key6  key4  key5
0      1     4     3     1    56     3
1      1     4     3     2     5    56
2      1     4     3    45     6     5
3      1     4     3     6     7     6
4      1     4     3    67     8     6
5      2     5     4     1    56     3
6      2     5     4     2     5    56
7      2     5     4    45     6     5
8      2     5     4     6     7     6
9      2     5     4    67     8     6
10     4     6     5     1    56     3
11     4     6     5     2     5    56
12     4     6     5    45     6     5
13     4     6     5     6     7     6
14     4     6     5    67     8     6
15     5     7     6     1    56     3
16     5     7     6     2     5    56
17     5     7     6    45     6     5
18     5     7     6     6     7     6
19     5     7     6    67     8     6
20     6     8     6     1    56     3
21     6     8     6     2     5    56
22     6     8     6    45     6     5
23     6     8     6     6     7     6
24     6     8     6    67     8     6

In [32]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [33]:
df.Fare

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [34]:
df['Fare'].apply(lambda x:x*90)

0       652.500
1      6415.497
2       713.250
3      4779.000
4       724.500
         ...
886    1170.000
887    2700.000
888    2110.500
889    2700.000
890     697.500
Name: Fare, Length: 891, dtype: float64

In [35]:
df['Fare_inr']=df['Fare'].apply(lambda x:x*90)

In [36]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500

In [37]:
df['Fare_inr']

0       652.500
1      6415.497
2       713.250
3      4779.000
4       724.500
         ...
886    1170.000
887    2700.000
888    2110.500
889    2700.000
890     697.500
Name: Fare_inr, Length: 891, dtype: float64

In [38]:
len("ram")

3

In [39]:
df["Name_len"]=df['Name'].apply(len)

In [40]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19

In [41]:
def convert(x):
    return x*83

In [42]:
df['Fare_1']=df['Fare'].apply(convert)

In [43]:
df['Fare_1']

0       601.7500
1      5916.5139
2       657.7750
3      4407.3000
4       668.1500
         ...
886    1079.0000
887    2490.0000
888    1946.3500
889    2490.0000
890     643.2500
Name: Fare_1, Length: 891, dtype: float64

In [44]:
def create_flag(a):
    if a < 10:
        return "chip"
    if a>10 and a<50:
        return "medium"
    else:
        return "high"

In [45]:
df['flag_fare'] = df['Fare'].apply(create_flag)

In [46]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare_1,flag_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,601.7500,chip
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,5916.5139,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,657.7750,chip
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4407.3000,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,668.1500,chip
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1079.0000,medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2490.0000,medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,1946.3500,medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2490.0000,medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,643.2500,chip

In [47]:
data = {"a":[1,2,3,4],
        "b":[5,5,6,7],
        "c":["pw","skills","aj", "cj"]}
df1=pd.DataFrame(data)

In [48]:
df1

   a  b       c
0  1  5      pw
1  2  5  skills
2  3  6      aj
3  4  7      cj

In [49]:
df1.set_index('c', inplace=True)

In [50]:
df1

        a  b
c
pw      1  5
skills  2  5
aj      3  6
cj      4  7

In [51]:
df1.reset_index()

        c  a  b
0      pw  1  5
1  skills  2  5
2      aj  3  6
3      cj  4  7

In [52]:
df1.reset_index(drop=True,inplace=True)

In [53]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [54]:
df1.reindex([1,2,3,0])

   a  b
1  2  5
2  3  6
3  4  7
0  1  5

In [55]:
for i in df1.iterrows(): #itrasion is row wise
    print(i,"``````````````````")

(0, a    1
b    5
Name: 0, dtype: int64) ``````````````````
(1, a    2
b    5
Name: 1, dtype: int64) ``````````````````
(2, a    3
b    6
Name: 2, dtype: int64) ``````````````````
(3, a    4
b    7
Name: 3, dtype: int64) ``````````````````

In [56]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [57]:
for i in df1.items(): #column wise itrasion
    print(i,"......................")

('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64) ......................
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64) ......................

In [58]:
def func_sum(x):
    return x.sum()

In [59]:
df1.apply(func_sum, axis=0)

a    10
b    23
dtype: int64

In [60]:
df1.apply(func_sum, axis=1)

0     6
1     7
2     9
3    11
dtype: int64

In [61]:
#use function in datafram
df1.applymap(lambda x:x**2)

C:\Users\sujay\AppData\Local\Temp\ipykernel_8324\1146658176.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x:x**2)

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [62]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [63]:
df1.sort_values(by='a')

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [64]:
data = {"a":[1,2,6,2,5,9,12,45,78,123,567,3,4],
        "b":[1,2,6,2,5,9,12,45,78,123,567,3,4],}

df3=pd.DataFrame(data)

In [65]:
df3

      a    b
0     1    1
1     2    2
2     6    6
3     2    2
4     5    5
5     9    9
6    12   12
7    45   45
8    78   78
9   123  123
10  567  567
11    3    3
12    4    4

In [66]:
df3.sort_values(by ='a')

      a    b
0     1    1
1     2    2
3     2    2
11    3    3
12    4    4
4     5    5
2     6    6
5     9    9
6    12   12
7    45   45
8    78   78
9   123  123
10  567  567

In [67]:
df.sort_values(by="Fare")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare_1,flag_fare
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S,0.000,28,0.0000,chip
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0000,NaN,S,0.000,19,0.0000,chip
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S,0.000,31,0.0000,chip
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S,0.000,29,0.0000,chip
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0000,NaN,S,0.000,27,0.0000,chip
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,23670.000,17,21829.0000,high
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,23670.000,30,21829.0000,high
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,46109.628,22,42523.3236,high
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,46109.628,16,42523.3236,high
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,46109.628,34,42523.3236,high